### ISSUE TITLE
Slight improvement for Version on collapsed line

### ISSUE THREAD

**Issue by TasMot** [TrianguloY/mavenDependencyCollapse#2]
Currently, I have a project where the collapsed dependency line shows as: 	
<dependency com.flow.api : flow-util : ${project.version} : provided >

The ${project.version} is actually defined in the parent POM because it is used in multiple sub-projects of the parent.  If I hit Ctl-Alt-B, Intellij correctly locates the property in the parent and jumps to it. However; this great plugin only resolves the property if it is in the current POM, not the parent POM. Can this be done also?
Thanks,
Tom

**Comment by TrianguloY** [comment]
Oh! Happy to hear someone other than me uses this 😅

I know what you are referring to, I have the same issue. This is because the current implementation simply uses the Jetbrains Sdk to extract the data from the context, which is the file.

However, as you said, IntelliJ does know of the origin of the property, I wonder if you can "extract" and use that information 🤔

I'll investigate, but I don't promise anything. Still, if someone knows and wants to help (or point to documentation) that will be greatly appreciated!

**Comment by TrianguloY** [comment]
I think I found it!
Next version (available probably tomorrow) will fix the project.version, and any other template that the IDE can detect.
I'm going to close this as fixed, but if you find any issue with this or other templates don't hesitate to reopen or create a new issue.
